os: Visual Studio 2015
version: 1.0.{build}
install:
  # Download SDL.
  - ps: Start-FileDownload 'https://buildbot.libsdl.org/sdl-builds/sdl-visualstudio/sdl-visualstudio-2568.zip' 'RecastDemo/Contrib/SDL.zip'
  
  # Extract it and put it in the right place.
  - cd RecastDemo/Contrib && 7z x SDL.zip && cd ../..

  # Fetch the submodules
  - git submodule update --init --recursive

configuration: Release
platform: Win32

build:
  project: recastnavigation.sln

after_build:
  # Copy all required files to output
  - ps: Copy-Item .\Bin\Release -Destination .\output\bin -Recurse -Container
  - ps: Copy-Item .\Lib\Release\*.lib -Destination .\output\lib; 
  - ps: mkdir .\output\include
  - ps: Get-ChildItem .\DebugUtils\Include -Filter "*.h" | % { Copy-Item -Path $_.FullName -Destination ".\output\include\$($_.Name)" }
  - ps: Get-ChildItem .\Detour*\Include -Filter "*.h" | % { Copy-Item -Path $_.FullName -Destination ".\output\include\$($_.Name)" }
  - ps: Get-ChildItem .\Recast\Include -Filter "*.h" | % { Copy-Item -Path $_.FullName -Destination ".\output\include\$($_.Name)" }
  - ps: Copy-Item .\License.txt .\output\License.txt
  - cd ouput
  - 7z a release.zip *

artifacts:
- path: output\release.zip
  name: "recastnavigation-{version}.zip"