# Set image for the build
os: Visual Studio 2015
# Set version for the build
version: 1.0.{build}
# Install required build dependencies
install:
  # Download SDL.
  - ps: Start-FileDownload 'https://buildbot.libsdl.org/sdl-builds/sdl-visualstudio/sdl-visualstudio-2568.zip' 'RecastDemo/Contrib/SDL.zip'
  
  # Extract it and put it in the right place.
  - cd RecastDemo/Contrib && 7z x SDL.zip && cd ../..

  # Fetch the submodules
  - git submodule update --init --recursive

  # Install doxygen
  - choco install doxygen.portable

# Set Configuration and Platform for the build
configuration: Release
platform: Win32

# Start the build
build:
  project: recastnavigation.sln

# Execute after build commands
after_build:
  # Copy all required files to output
- ps: >-
    mkdir .\output\bin

    mkdir .\output\lib

    mkdir .\output\include

    Copy-Item .\Bin\Release -Destination .\output\bin -Recurse -Container

    Copy-Item .\Lib\Release\*.lib -Destination .\output\lib

    Get-ChildItem .\Common\Include -Filter "*.h" | % { Copy-Item -Path $_.FullName -Destination ".\output\include\$($_.Name)" }

    Get-ChildItem .\DebugUtils\Include -Filter "*.h" | % { Copy-Item -Path $_.FullName -Destination ".\output\include\$($_.Name)" }

    Get-ChildItem .\Detour\Include -Filter "*.h" | % { Copy-Item -Path $_.FullName -Destination ".\output\include\$($_.Name)" }

    Get-ChildItem .\DetourCrowd\Include -Filter "*.h" | % { Copy-Item -Path $_.FullName -Destination ".\output\include\$($_.Name)" }

    Get-ChildItem .\DetourTileCache\Include -Filter "*.h" | % { Copy-Item -Path $_.FullName -Destination ".\output\include\$($_.Name)" }

    Get-ChildItem .\Recast\Include -Filter "*.h" | % { Copy-Item -Path $_.FullName -Destination ".\output\include\$($_.Name)" }

    Copy-Item .\License.txt .\output\License.txt

  # Generate build artifact and push it to appveyor
- ps: >-
    cd output

    7z a release.zip *

    cd ..

    Move-Item .\output\release.zip ".\recastnavigation-$($env:APPVEYOR_BUILD_VERSION).zip"

    Push-AppveyorArtifact ".\recastnavigation-$($env:APPVEYOR_BUILD_VERSION).zip"

  # Generate doxygen output
- ps: doxygen.exe .\Doxyfile
